version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db  # Mounts the data folder for persistent storage

  backend:
    build:
      context: ./mha-backend
      dockerfile: Dockerfile  
    container_name: mha-backend
    environment:
      - MONGO_URI=mongodb://db:27017/test
    ports:
      - "5000:5000"  # Expose backend port
    depends_on:
      - db  